# Generated by Django 6.0.3 on 2026-03-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('tech', models.CharField(max_length=200)),
                ('github_link', models.TextField(default=None)),
                ('live_link', models.TextField(default=None)),
            ],
        ),
    ]
